apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: stateful-canary
  namespace: argocd
spec: 
  destination: 
    namespace: stateful
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: ./
    repoURL: "https://github.com/VarunNagesh/stateful-canary-ingress.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
